In [1]:
%load_ext autoreload
%autoreload 2
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import warnings
warnings.filterwarnings("ignore")

import os
import pandas as pd
import sys
sys.path.insert(0, '/home/kat/Repos/SALSA/')

In [2]:
seedy = 666
df = pd.read_csv('data/chembl_valid_10to30atoms.csv')

samp_size = 1000

df_samp = df.sample(samp_size, random_state=seedy)
df_samp['len'] = df_samp.smiles.apply(lambda x: len(x))
df_samp = df_samp.sort_values(by='len',ignore_index=True)

In [3]:
def get_augset_from_src(k,v,aug_iter):
        
    src_idx = v[0]
    anc_idx = v[1]
    smi = v[4]

    augs = get_ext_augs(smi)
    augs = list(set(augs))
    
    augset = []
    if augs:
        for aug_smi in augs:
            tup = [anc_idx, src_idx, aug_iter, aug_smi]
            if tup not in augset:
                augset.append(tup)
    return augset

In [4]:
import numpy as np
from tqdm.notebook import tqdm

from extended_augs_utils import get_ext_augs
from joblib import Parallel, delayed

iters = 10
max_augs = 10

for aug_iter in tqdm(range(iters+1), total=(iters+1)):
    
    curr_augset = []
    
    if aug_iter==0:
        for row in df_samp.itertuples():
            idx = row.Index
            anc_idx = idx
            src_idx = idx
            smi = row.smiles
            tup = [idx, anc_idx, src_idx, aug_iter, smi]
            curr_augset.append(tup)
            df_augset = pd.DataFrame(curr_augset, columns=['idx','anc_idx','src_idx', 'aug_iter', 'smiles'])
        
    else:
        df_src = df_augset[df_augset.aug_iter==(aug_iter-1)]
        dict_src = df_src.T.to_dict('list')
            
        parallelizer = Parallel(n_jobs=-1, backend='multiprocessing' )
        tasks = (delayed(get_augset_from_src)(k,v,aug_iter) for k,v in dict_src.items())
        curr_augset = parallelizer(tasks)
        curr_augset = [x for l in curr_augset for x in l]
        
        
        print(len(df_src), len(curr_augset))
        
        
        curr_augset = pd.DataFrame(curr_augset, columns=['anc_idx', 'src_idx', 'aug_iter', 'smiles'])
        
        
        id_idc = [int(i) for i in range(len(df_src), len(curr_augset)+len(df_src))]
        print(len(id_idc))
#         print(id_idc)
        curr_augset['idx'] = id_idc
        curr_augset = curr_augset[['idx','anc_idx','src_idx', 'aug_iter', 'smiles']]
        display(curr_augset)
#         break
        
#         curr_augset = pd.DataFrame(curr_augset, columns=['anc_idx', 'src_idx', 'aug_iter', 'smiles'])
        curr_augset.drop_duplicates(keep='first', inplace=True)
#         display(curr_augset)
        
        trunc_idc = []
        for i in range(len(df_samp)):
            df_anc = curr_augset[curr_augset.anc_idx==i]
            df_anc = df_anc.sample(n=10, replace=True)
            idc = df_anc.index.values
            trunc_idc.extend(idc)
        trunc_augset = curr_augset.iloc[trunc_idc]
        
        df_augset = pd.concat([df_augset, trunc_augset], axis=0)
        
        display(df_augset)

  0%|          | 0/11 [00:00<?, ?it/s]

1000 9153
9153

,idx,anc_idx,src_idx,aug_iter,smiles
0,1000,0,0,1,CCCN(CC(O)CN)N=O
1,1001,0,0,1,CCCN(CC(C)(C)O)N=O
2,1002,0,0,1,CCCN(CC(C)OC)N=O
3,1003,0,0,1,CCCN(N=O)C(C)C(C)O
4,1004,0,0,1,CCC(C)N(CC(C)O)N=O
...,...,...,...,...,...
9148,10148,999,999,1,Cc1c([N+](=O)[O-])ccc(N2C(=O)c3cccc4cccc(c34)C...
9149,10149,999,999,1,Cc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1N1C(=O)c2...
9150,10150,999,999,1,O=C1c2cccc3cc(S)cc(c23)C(=O)N1c1ccc([N+](=O)[O...
9151,10151,999,999,1,O=C1c2cccc3ccc(O)c(c23)C(=O)N1c1ccc([N+](=O)[O...
9152,10152,999,999,1,O=C1c2cccc3cccc(c23)C(=O)N1c1cc(O)c([N+](=O)[O...

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
9148,10148,999,999,1,Cc1c([N+](=O)[O-])ccc(N2C(=O)c3cccc4cccc(c34)C...
9145,10145,999,999,1,Cc1ccc2cccc3c2c1C(=O)N(c1ccc([N+](=O)[O-])cc1[...
9148,10148,999,999,1,Cc1c([N+](=O)[O-])ccc(N2C(=O)c3cccc4cccc(c34)C...
9147,10147,999,999,1,Cc1ccc2c3c(cccc13)C(=O)N(c1ccc([N+](=O)[O-])cc...
9150,10150,999,999,1,O=C1c2cccc3cc(S)cc(c23)C(=O)N1c1ccc([N+](=O)[O...

10000 58909
58909

,idx,anc_idx,src_idx,aug_iter,smiles
0,10000,0,1007,2,CCCN(CC(C)(O)CC)N=O
1,10001,0,1007,2,CCCN(CC(O)C(C)C)N=O
2,10002,0,1007,2,CCCN(CC(CC)OO)N=O
3,10003,0,1007,2,CCCCN(CC(O)CC)N=O
4,10004,0,1007,2,CCCC(O)CN(CCC)N=O
...,...,...,...,...,...
58904,68904,999,10147,2,Cc1ccc2c3c(ccc(O)c13)C(=O)N(c1ccc([N+](=O)[O-]...
58905,68905,999,10147,2,Cc1cc(C)c2cccc3c2c1C(=O)N(c1ccc([N+](=O)[O-])c...
58906,68906,999,10147,2,Cc1cc(N2C(=O)c3cccc4c(C)ccc(c34)C2=O)c([N+](=O...
58907,68907,999,10147,2,CCc1ccc2c3c(cccc13)C(=O)N(c1ccc([N+](=O)[O-])c...
58908,68908,999,10147,2,Cc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1N1C(=O)c2...

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
58857,68857,999,10148,2,Cc1cc(N2C(=O)c3cccc4cccc(c34)C2=O)c([N+](=O)[O...
58862,68862,999,10148,2,Cc1c([N+](=O)[O-])ccc(N2C(=O)c3cccc4c(O)ccc(c3...
58889,68889,999,10150,2,Cc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1N1C(=O)c2...
58882,68882,999,10150,2,O=C1c2ccc(O)c3cc(S)cc(c23)C(=O)N1c1ccc([N+](=O...
58861,68861,999,10148,2,Cc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=O...

10000 87878
87878

,idx,anc_idx,src_idx,aug_iter,smiles
0,10000,0,10019,3,CC(C)CCN(CC(C)(C)O)N=O
1,10001,0,10019,3,CCC(O)CN(CCC(C)C)N=O
2,10002,0,10019,3,CC(O)CN(CCC(C)(C)C)N=O
3,10003,0,10019,3,CCC(C)CCN(CC(C)O)N=O
4,10004,0,10019,3,CC(C)CCN(N=O)C(O)C(C)O
...,...,...,...,...,...
87873,97873,999,68861,3,Cc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=O...
87874,97874,999,68861,3,Cc1c(C)c([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C...
87875,97875,999,68861,3,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
87876,97876,999,68861,3,Cc1cc2c3c(cccc3c1)C(=O)N(c1c(C)cc([N+](=O)[O-]...
87877,97877,999,68861,3,CCc1c([N+](=O)[O-])cc(C)c(N2C(=O)c3cccc4cccc(c...

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
87851,97851,999,68862,3,Cc1ccc2c(O)ccc3c2c1C(=O)N(c1ccc([N+](=O)[O-])c...
87793,97793,999,68887,3,Cc1cc2c3c(cc(S)cc3c1)C(=O)N(c1ccc([N+](=O)[O-]...
87819,97819,999,68896,3,CCc1ccc2cccc3c2c1C(=O)N(c1cc(C)c([N+](=O)[O-])...
87818,97818,999,68896,3,CCCc1ccc2cccc3c2c1C(=O)N(c1ccc([N+](=O)[O-])cc...
87860,97860,999,68889,3,Cc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1N1C(=O)c2...

10000 91200
91200

,idx,anc_idx,src_idx,aug_iter,smiles
0,10000,0,10001,4,CCCC(O)CN(CCC(C)C)N=O
1,10001,0,10001,4,CC(C)CCN(CC(O)C(C)C)N=O
2,10002,0,10001,4,CCC(O)C(C)N(CCC(C)C)N=O
3,10003,0,10001,4,CCC(O)CN(CCC(C)(C)O)N=O
4,10004,0,10001,4,CCC(CN(CCC(C)C)N=O)OC
...,...,...,...,...,...
91195,101195,999,97860,4,Cc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1N1C(=O)c2...
91196,101196,999,97860,4,Cc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1N1C(=O)c2...
91197,101197,999,97860,4,CCc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1N1C(=O)c...
91198,101198,999,97860,4,Cc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=O...
91199,101199,999,97860,4,Cc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1N1C(=O)c2...

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
91125,101125,999,97862,4,Cc1c(S)cc2c3c(ccc(OCl)c13)C(=O)N(c1ccc([N+](=O...
91149,101149,999,97872,4,Cc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=O...
91180,101180,999,97819,4,CCc1ccc2cccc3c2c1C(=O)N(c1c([N+](=O)[O-])cc([N...
91116,101116,999,97821,4,CCc1cc(C)c2ccc(C)c3c2c1C(=O)N(c1ccc([N+](=O)[O...
91181,101181,999,97818,4,CCCc1ccc2ccc(C)c3c2c1C(=O)N(c1ccc([N+](=O)[O-]...

10000 92403
92403

,idx,anc_idx,src_idx,aug_iter,smiles
0,10000,0,10091,5,CCCCN(N=O)C(CC)C(CC)OC
1,10001,0,10091,5,CCCC(C)N(N=O)C(C)C(CC)OC
2,10002,0,10091,5,CCCCN(N=O)C(C)C(OC)C(C)C
3,10003,0,10091,5,CCC(OC)C(C)N(CCC(C)C)N=O
4,10004,0,10091,5,CCC(C)CN(N=O)C(C)C(CC)OC
...,...,...,...,...,...
92398,102398,999,101181,5,CCC(C)c1ccc2ccc(C)c3c2c1C(=O)N(c1ccc([N+](=O)[...
92399,102399,999,101181,5,CCCc1ccc2ccc(CC)c3c2c1C(=O)N(c1ccc([N+](=O)[O-...
92400,102400,999,101181,5,CCCc1ccc2ccc(C)c3c2c1C(=O)N(c1c(C)cc([N+](=O)[...
92401,102401,999,101181,5,CCCc1ccc2ccc(C)c3c2c1C(=O)N(c1ccc([N+](=O)[O-]...
92402,102402,999,101181,5,CCCc1ccc2c(O)cc(C)c3c2c1C(=O)N(c1ccc([N+](=O)[...

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
92377,102377,999,101180,5,CCc1ccc2cc(C)cc3c2c1C(=O)N(c1c([N+](=O)[O-])cc...
92361,102361,999,101166,5,CSc1cc2c3c(cc(C)c(C)c3c1)C(=O)N(c1ccc([N+](=O)...
92366,102366,999,101149,5,Cc1cc2c3c(c(N)c(O)cc3c1)C(=O)N(c1c(C)cc([N+](=...
92385,102385,999,101116,5,CCc1ccc2c(C)cc(CC)c3c2c1C(=O)N(c1ccc([N+](=O)[...
92374,102374,999,101180,5,Cc1c([N+](=O)[O-])cc([N+](=O)[O-])c(N2C(=O)c3c...

10000 92464
92464

,idx,anc_idx,src_idx,aug_iter,smiles
0,10000,0,10019,6,CCCCN(N=O)C(C)C(CCOC)OO
1,10001,0,10019,6,CCCCN(N=O)C(CC)C(O)CCOC
2,10002,0,10019,6,CCCC(N)N(N=O)C(C)C(O)CCOC
3,10003,0,10019,6,CCCCN(N=O)C(C)C(C)(O)CCOC
4,10004,0,10019,6,CCC(C)CN(N=O)C(C)C(O)CCOC
...,...,...,...,...,...
92459,102459,999,102374,6,Cc1c([N+](=O)[O-])cc([N+](=O)[O-])c(N2C(=O)c3c...
92460,102460,999,102374,6,CCc1c([N+](=O)[O-])cc([N+](=O)[O-])c(N2C(=O)c3...
92461,102461,999,102374,6,Cc1c([N+](=O)[O-])cc([N+](=O)[O-])c(N2C(=O)c3c...
92462,102462,999,102374,6,Cc1c([N+](=O)[O-])cc([N+](=O)[O-])c(N2C(=O)c3c...
92463,102463,999,102374,6,CCc1c(C)c([N+](=O)[O-])cc([N+](=O)[O-])c1N1C(=...

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
92412,102412,999,102353,6,CSc1cc2c3c(cc(C)cc3c1O)C(=O)N(c1c(C)cc([N+](=O...
92434,102434,999,102361,6,Cc1cc2c3c(cc([SH](C)C)cc3c1C)C(=O)N(c1ccc([N+]...
92453,102453,999,102385,6,CCc1ccc2c(C)cc(CC)c3c2c1C(=O)N(c1c(O)cc([N+](=...
92389,102389,999,102386,6,CCc1cc(CC)c2c(O)cc(C)c3c2c1C(=O)N(c1ccc([N+](=...
92372,102372,999,102321,6,Cc1cc(C)c2c(C)cc(C(C)S)c3c2c1C(=O)N(c1ccc([N+]...

10000 93270
93270

,idx,anc_idx,src_idx,aug_iter,smiles
0,10000,0,10001,7,CCCC(C)N(N=O)C(CC)C(O)CCOC
1,10001,0,10001,7,CCCCN(N=O)C(C)(CC)C(O)CCOC
2,10002,0,10001,7,CCCCN(N=O)C(CC)C(CCOC)OC
3,10003,0,10001,7,CCCCN(N=O)C(CC)C(C)(O)CCOC
4,10004,0,10001,7,CCC(C(O)CCOC)N(CCC(C)O)N=O
...,...,...,...,...,...
93265,103265,999,102372,7,Cc1cc(C)c2c(C)cc(C(C)(C)S)c3c2c1C(=O)N(c1ccc([...
93266,103266,999,102372,7,Cc1cc(CBr)c2c(C)cc(C(C)S)c3c2c1C(=O)N(c1ccc([N...
93267,103267,999,102372,7,CCc1cc(C)c2c(C)cc(C(C)S)c3c2c1C(=O)N(c1ccc([N+...
93268,103268,999,102372,7,Cc1cc(C)c2c(C)c(C)c(C(C)S)c3c2c1C(=O)N(c1ccc([...
93269,103269,999,102372,7,Cc1cc(N2C(=O)c3c(C)cc(C)c4c(C)cc(C(C)S)c(c34)C...

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
93229,103229,999,102412,7,CCc1cc([N+](=O)[O-])c(S)c([N+](=O)[O-])c1N1C(=...
93192,103192,999,102384,7,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93192,103192,999,102384,7,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93247,103247,999,102453,7,CCc1ccc2c(C)cc(C(C)C)c3c2c1C(=O)N(c1c(O)cc([N+...
93196,103196,999,102384,7,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...

10000 93637
93637

,idx,anc_idx,src_idx,aug_iter,smiles
0,10000,0,10054,8,CCCC(CN)CN(N=O)C(C)C(OC)C(C)C
1,10001,0,10054,8,CCCC(C)CN(N=O)C(C)C(OC)C(C)CO
2,10002,0,10054,8,CCCC(C)CN(N=O)C(C)C(OC)C(C)CC
3,10003,0,10054,8,CCCC(C)C(N)N(N=O)C(C)C(OC)C(C)C
4,10004,0,10054,8,CCCC(C)CN(N=O)C(C)C(N)(OC)C(C)C
...,...,...,...,...,...
93632,103632,999,103196,8,CNc1c(O)cc2c(C)ccc3c2c1C(=O)N(c1c(C(C)C)cc([N+...
93633,103633,999,103196,8,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93634,103634,999,103196,8,CCc1cc([N+](=O)[O-])c(CC)c([N+](=O)[O-])c1N1C(...
93635,103635,999,103196,8,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93636,103636,999,103196,8,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
93603,103603,999,103261,8,CCc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1N1C(=O)c...
93585,103585,999,103199,8,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93602,103602,999,103261,8,Cc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=O...
93584,103584,999,103199,8,Cc1c([N+](=O)[O-])cc(C(C)O)c(N2C(=O)c3cccc4cc(...
93558,103558,999,103218,8,CSc1cc2c3c(c(CO)c(C)c(C)c3c1)C(=O)N(c1ccc([N+]...

10000 94102
94102

,idx,anc_idx,src_idx,aug_iter,smiles
0,10000,0,10031,9,CCC(C(O)CCOC)N(CCC(C)(O)ON)N=O
1,10001,0,10031,9,CCC(C)(C(O)CCOC)N(CCC(C)(O)O)N=O
2,10002,0,10031,9,COCCC(O)C(C(C)C)N(CCC(C)(O)O)N=O
3,10003,0,10031,9,CCC(C(O)CCOC)N(CC(C)C(C)(O)O)N=O
4,10004,0,10031,9,CCC(C(CCOC)OC)N(CCC(C)(O)O)N=O
...,...,...,...,...,...
94097,104097,999,103558,9,CCc1c(CO)c2c3c(cc(SC)cc3c1C)C(=O)N(c1ccc([N+](...
94098,104098,999,103558,9,CSc1cc2c3c(c(CO)c(C)c(C)c3c1)C(=O)N(c1cc(C)c([...
94099,104099,999,103558,9,CSc1cc2c3c(c(CO)c(C)c(C)c3c1N)C(=O)N(c1ccc([N+...
94100,104100,999,103558,9,CSc1cc2c3c(c(C(C)O)c(C)c(C)c3c1)C(=O)N(c1ccc([...
94101,104101,999,103558,9,CSc1cc2c3c(c(CO)c(C)c(C)c3c1)C(=O)N(c1c(C)cc([...

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
94070,104070,999,103585,9,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
94085,104085,999,103584,9,CCC(O)c1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N...
94014,104014,999,103622,9,CCCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(...
94050,104050,999,103618,9,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
94071,104071,999,103585,9,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...

10000 93830
93830

,idx,anc_idx,src_idx,aug_iter,smiles
0,10000,0,10004,10,CCC(C(CCOC)OC)N(CCC(O)(O)CC)N=O
1,10001,0,10004,10,CCC(C(CCOC)OC)N(CCC(C)(O)OC)N=O
2,10002,0,10004,10,CCCC(C(CCOC)OC)N(CCC(C)(O)O)N=O
3,10003,0,10004,10,CCC(C(CCOC)OC)N(CC(C)C(C)(O)O)N=O
4,10004,0,10004,10,CCC(C)(C(CCOC)OC)N(CCC(C)(O)O)N=O
...,...,...,...,...,...
93825,103825,999,104071,10,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93826,103826,999,104071,10,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93827,103827,999,104071,10,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93828,103828,999,104071,10,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93829,103829,999,104071,10,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
93738,103738,999,104043,10,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93803,103803,999,104014,10,CCCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(...
93809,103809,999,104014,10,CCCCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C...
93749,103749,999,104056,10,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93802,103802,999,104014,10,CCCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(...

In [5]:
df_augset

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
93738,103738,999,104043,10,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93803,103803,999,104014,10,CCCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(...
93809,103809,999,104014,10,CCCCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C...
93749,103749,999,104056,10,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93802,103802,999,104014,10,CCCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(...

In [6]:
df_augset_nodups = df_augset.drop_duplicates(keep='first')
df_augset_nodups

,idx,anc_idx,src_idx,aug_iter,smiles
0,0,0,0,0,CCCN(CC(C)O)N=O
1,1,1,1,0,Cn1cncc1C(=O)NN
2,2,2,2,0,S=c1ssc2c1CCCCC2
3,3,3,3,0,Cc1csc2nc(N)nn12
4,4,4,4,0,CCCOC(=O)c1ccccc1
...,...,...,...,...,...
93794,103794,999,104085,10,CCc1c([N+](=O)[O-])cc(C(O)CC)c(N2C(=O)c3cccc4c...
93738,103738,999,104043,10,CCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(=...
93803,103803,999,104014,10,CCCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(...
93809,103809,999,104014,10,CCCCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C...
93802,103802,999,104014,10,CCCc1cc([N+](=O)[O-])c(C)c([N+](=O)[O-])c1N1C(...

In [7]:
df_augset_nodups.to_csv('20220603_extended_augset_1000anc_10iters.csv',index=False)